import Image from "next/image";

export const metadata = {
  title: "Alfred Hutomo - About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main className="flex flex-col px-7 sm:py-[80px] sm:px-[100px] w-full flex-1">
      <section className="about-content">
        <h2>About Me</h2>
      </section>
    </main>
  );
}
