import Image from "next/image";

export const metadata = {
  title: "Alfred Hutomo - Work",
  description: "Generated by create next app",
};

export default function Work() {
  return (
    <main className="relative flex place-items-center min-h-full">
      <Image
        className="relative"
        src="/assets/large_ah_logo.svg"
        alt="AH Logo"
        // className="dark:invert"
        width={400}
        height={24}
        priority
      />
    </main>
  );
}
